{"status":"fatal","errors":["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/python_driver/requestprocessor.py\", line 152, in process_request\n    raise Exception('Could not determine Python version')\nException: Could not determine Python version\n"],"uast":null}
